# Home Assistant Sensor Configuration for SmartPantry
# Add this to your configuration.yaml

# ========== SMART PANTRY SENSORS ==========

# Main pantry sensor - all items
sensor:
  - platform: rest
    name: "SmartPantry All Items"
    unique_id: "smart_pantry_all_items"
    resource: "https://smartpantry.vercel.app/api/pantry"
    scan_interval: 300  # Refresh every 5 minutes
    value_template: "{{ value_json.items | length }}"
    json_attributes:
      - items
    headers:
      Content-Type: "application/json"

# Expiring within 3 days
sensor:
  - platform: rest
    name: "SmartPantry Expiring Soon"
    unique_id: "smart_pantry_expiring_3"
    resource: "https://smartpantry.vercel.app/api/pantry?expiring=3"
    scan_interval: 300
    value_template: "{{ value_json.items | length }}"
    json_attributes:
      - items
    headers:
      Content-Type: "application/json"

# Template sensors for convenience
template:
  - sensor:
      - name: "Pantry Next Expiry"
        state: >
          {% set items = state_attr('sensor.smart_pantry_all_items', 'items') %}
          {% if items and items | length > 0 %}
            {% set sorted = items | sort(attribute='expiration_date') %}
            {{ sorted[0].name }}
          {% else %}
            Empty
          {% endif %}
        icon: mdi:calendar-alert

      - name: "Pantry Total Quantity"
        state: >
          {% set items = state_attr('sensor.smart_pantry_all_items', 'items') %}
          {% if items %}
            {{ items | sum(attribute='quantity') }}
          {% else %}
            0
          {% endif %}
        icon: mdi:package-variant
